services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_MAX_WORKERS=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
